import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import axios from "axios";

export async function getServerSideProps() {
  const [profile, repos] = await Promise.all([
    axios.get("https://api.github.com/users/fl4wn"),
    axios.get("https://api.github.com/users/fl4wn/repos"),
  ]);

  return {
    props: {
      profile: profile.data,
      repos: repos.data,
    },
  };
}

const Home: NextPage = ({ profile, repos }: any) => {
  return (
    <div className="text-white min-h-screen px-2 bg-gradient-to-br from-stone-900 to-neutral-900">
      <Head>
        <title>Alkım Caner Soydan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-[48rem] mx-auto">
        <h1 className="text-center h-20 pt-4 font-extrabold text-transparent text-4xl bg-clip-text bg-gradient-to-r from-orange-400 to-pink-600">
          {profile.name}
        </h1>
        <div className="text-center text-gray-300">{profile.bio}</div>

        <div className="flex flex-col items-center gap-8 mt-8 md:flex-row">
          <div className="relative w-64 h-64 rounded-2xl overflow-hidden">
            <Image src={profile.avatar_url} layout="fill"></Image>
          </div>
          <div className="w-full md:w-1/2">
            <h2 className="h-12 font-extrabold text-transparent text-3xl bg-clip-text bg-gradient-to-r from-teal-600 to-amber-400">
              About me
            </h2>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad unde
              rem veritatis tempora eum facere totam nesciunt commodi incidunt
              at voluptas neque adipisci accusantium, ratione ut sequi cumque,
              ducimus nam.Lorem ipsum dolor sit amet consectetur adipisicing
              elit. Ad unde rem veritatis tempora eum facere totam nesciunt
              commodi incidunt at voluptas neque adipisci accusantium, ratione
              ut sequi cumque, ducimus nam.
            </p>
          </div>
        </div>

        <div className="mt-8">
          <h2 className="h-12 font-extrabold text-transparent text-3xl bg-clip-text bg-gradient-to-r from-indigo-500 to-rose-500">
            Repositories
          </h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad unde rem
            veritatis tempora eum facere totam nesciunt commodi incidunt at
            voluptas neque adipisci accusantium, ratione ut sequi cumque,
            ducimus nam.Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Ad unde rem veritatis tempora eum facere totam nesciunt commodi
            incidunt at voluptas neque adipisci accusantium, ratione ut sequi
            cumque, ducimus nam.
          </p>
        </div>
        <div className="mt-8">
          <h2 className="h-12 font-extrabold text-transparent text-3xl bg-clip-text bg-gradient-to-r from-rose-500 to-slate-100">
            Contact me
          </h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad unde rem
            veritatis tempora eum facere totam nesciunt commodi incidunt at
            voluptas neque adipisci accusantium, ratione ut sequi cumque,
            ducimus nam.Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Ad unde rem veritatis tempora eum facere totam nesciunt commodi
            incidunt at voluptas neque adipisci accusantium, ratione ut sequi
            cumque, ducimus nam.Lorem ipsum dolor sit amet consectetur
            adipisicing elit.
          </p>
        </div>
      </main>

      <footer className="mt-4">
        <div className="text-center text-gray-300 p-2">
          <p>
            Built with
            {` `}
            <a className="hover:text-blue-500" href="https://nextjs.org/">
              Next.js
            </a>
          </p>
          <p>© {new Date().getFullYear()}, Alkım Caner Soydan</p>
        </div>
      </footer>
    </div>
  );
};

export default Home;
